# Generated by Django 6.1.1 on 2026-09-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileLoad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Начало загрузки"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Окончание"
                    ),
                ),
                (
                    "rows_count",
                    models.IntegerField(default=0, verbose_name="Всего строк"),
                ),
                (
                    "loaded_count",
                    models.IntegerField(default=0, verbose_name="Загружено"),
                ),
                ("error_count", models.IntegerField(default=0, verbose_name="Ошибок")),
                (
                    "duplicate_count",
                    models.IntegerField(default=0, verbose_name="Дубликатов"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("PROCESSING", "В обработке"),
                            ("SUCCESS", "Успешно"),
                            ("FAILED", "Ошибка"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Загрузка файла",
                "verbose_name_plural": "Загрузки файлов",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inn",
                    models.CharField(max_length=10, unique=True, verbose_name="ИНН"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                ("region", models.CharField(max_length=255, verbose_name="Регион")),
                (
                    "employees",
                    models.PositiveIntegerField(verbose_name="Количество сотрудников"),
                ),
                (
                    "registration_date",
                    models.DateField(verbose_name="Дата регистрации"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="LoadError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(verbose_name="Номер строки")),
                ("raw_data", models.TextField(verbose_name="Исходные данные")),
                ("error_message", models.TextField(verbose_name="Описание ошибки")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="organizations.fileload",
                        verbose_name="Загрузка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ошибка загрузки",
                "verbose_name_plural": "Ошибки загрузки",
            },
        ),
    ]
